### ISSUE TITLE
Question on Evaluation

### ISSUE THREAD

**Issue by houjunlin** [deepdrdoc/Deep-Diabetic-Retinopathy-Image-Dataset-DeepDRiD-#1]
Thank you for your excellent work! I'd like to know how to evaluate the accuracy of the external dataset in Online-Challenge1&2-Evaluation, which is unlabeled?

Looking forward to your reply!

**Comment by sutummala** [comment]
Please provide labels for Evaluation dataset.

**Comment by deepdrdoc** [comment]
Thanks for your comments. We provided the labels now.
